class UserApplicationForm {
  String firstName;
  dynamic middleName;
  String lastName;
  String gender;
  String streetAddress;
  String addressLine2;
  String cityTownVillage;
  String postalZipCode;
  String country;
  String startDate;
  String previousStreetAddress;
  String previousAddressLine2;
  String previousCityTownVillage;
  String previousPostalZipCode;
  String previousCountry;
  String startDate2;
  String endDate2;
  String dateOfBirth;
  String phone;
  String email;
  String identificationDocument;
  String passportNumber;
  String countryOfIssue;
  String expiryDate;
  String biometricPermitNumber;
  String biometricPermitNumberExpiryDate;
  String ukDrivingLicenceNumber;
  String ukDrivingLicenceNumberExpiryDate;
  String maritalStatus;
  String dependents;
  String mortgageType;
  String mortgageProductType;
  String startDateOfMortgage;
  String maturityDateOfMortgage;
  String maturityDateOfInitialFixedRateOrTrackerPeriod;
  String currentMortgageRate;
  String outstandingBalanceOnMortgageGbp;
  String overpaymentsOnMortgageMadeInLast3YearsGbp;
  String propertyStreetAddress;
  String propertyAddressLine2;
  String propertyCityTownVillage;
  String propertyPostalZipCode;
  String propertyCountry;
  String currentPropertyValueEstimate;
  String typeOfProperty;
  String typeOfFlat;
  String approximateYearOfConstruction;
  String newBuildWarrantyProvider;
  String isYourPropertyAffectedByCladdingIssues;
  String anyOtherCoOwnersOfThisProperty;
  String howManyCoOwnersOfThisProperty;
  String anyOtherAdultsResidingInTheProperty;
  String howManyAdultsOtherThanYouResideInTheProperty;
  String statusOfEmployment;
  String plannedRetirementAge;
  String currentEmployerName;
  String jobDesignation;
  String howLongHaveYouBeenEmployedInThisJobInMonths;
  String annualIncomeFromCurrentEmploymentInGbp;
  bool additionalIncomeSources;
  List<String> additionalWorkRelatedPayments;
  String overtimePaymentsGbp;
  String frequencyOfOvertimePayments;
  String bonusPaymentsGbp;
  String frequencyOfBonusPayments;
  String commissionPaymentsGbp;
  String frequencyOfCommissionPayments;
  String allowanceAmountsGbp;
  String frequencyOfAllowancePayments;
  List<String> otherSourcesOfIncome;
  String pensionAmountsGbp;
  String frequencyOfPensionPayments;
  String investmentsGbp;
  String frequencyOfPaymentsFromInvestments;
  String disabilityBenefitsGbp;
  String frequencyOfDisabilityBenefits;
  String otherStateBenefitsGbp;
  String frequencyOfOtherStateBenefits;
  String maintenancePaymentsGbp;
  String frequencyOfMaintenancePayments;
  List<String> chooseWhichBorrowingsApplyToYourCircumstances;
  String whatIsTheOutstandingBalanceOnTheStudentLoanGbp;
  String whatAreTheMonthlyPaymentsDueOnTheStudentLoanGbp;
  String whatIsTheOutstandingBalanceOnTheUnsecuredPersonalLoanGbp;
  String whatAreTheMonthlyPaymentsDueOnTheUnsecuredPersonalLoanGbp;
  String whatIsTheRemainingTermOnTheUnsecuredPersonalLoanMonths;
  String whatIsTheOutstandingBalanceOnTheSecuredPersonalLoanGbp;
  String whatAreTheMonthlyPaymentsDueOnTheSecuredPersonalLoanGbp;
  String whatIsTheRemainingTermOnTheSecuredPersonalLoanMonths;
  String whatIsTheOutstandingBalanceOnTheCreditAgreementGbp;
  String whatAreMonthlyPaymentsDueOnTheCreditAgreementGbp;
  String whatIsTheRemainingTermOnTheCreditAgreementMonths;
  String whatIsTheOutstandingBalanceOnTheCarLoanGbp;
  String whatAreTheMonthlyPaymentsDueOnTheCarLoanGbp;
  String whatIsTheRemainingTermOnTheCarLoanMonths;
  String whatIsTheOutstandingBalanceOnTheLoanGuaranteesGbp;
  String whatAreTheMonthlyPaymentsDueOnTheLoanGuaranteesGbp;
  String whatIsTheRemainingTermOnTheLoanGuaranteesMonths;
  bool creditReference;
  List<String> cardsAndDebt;
  bool clickHereIfYouPayOffYourCreditCardBalanceEveryMonth;
  String whatIsTheOutstandingCreditCardBalanceGbp;
  dynamic whatIsYourOverdraftBalanceGbp;
  List<String> committedExpenses;
  String councilTaxPaymentsMonthFor10MonthsGbp;
  String buildingInsuranceYearGbp;
  String groundRentYearGbp;
  String serviceChargesYearGbp;
  String maintenancePaymentsYearGbp;
  String schoolFeesYearGbp;
  String dayCareOrNurseryFeesYearGbp;
  String yourSpecificRequirement;
  String monthlyMortgageOrCostOfLivingHelpNeededInGbp;
  String
      lengthOfTimeInMonthsYouNeedPauzibleSMortgageHelpPaymentsForMaxOf60Months;
  String productMaturityMaturityOfPauzibleSMortgageHelpProduct;
  String monthlyCashPaymentsNeededByYouInGbp;
  String lengthOfTimeInMonthsYouNeedPauziblePaymentsForMaxOf60Months;
  String productMaturityMaturityOfDesiredPauzibleProduct;
  String otherSourcesOfIncomeOtherOption;
  String chooseWhichBorrowingsApplyToYourCircumstancesOtherOption;
  String committedExpensesOtherOption;

  UserApplicationForm({
    required this.firstName,
    required this.middleName,
    required this.lastName,
    required this.gender,
    required this.streetAddress,
    required this.addressLine2,
    required this.cityTownVillage,
    required this.postalZipCode,
    required this.country,
    required this.startDate,
    required this.previousStreetAddress,
    required this.previousAddressLine2,
    required this.previousCityTownVillage,
    required this.previousPostalZipCode,
    required this.previousCountry,
    required this.startDate2,
    required this.endDate2,
    required this.dateOfBirth,
    required this.phone,
    required this.email,
    required this.identificationDocument,
    required this.passportNumber,
    required this.countryOfIssue,
    required this.expiryDate,
    required this.biometricPermitNumber,
    required this.biometricPermitNumberExpiryDate,
    required this.ukDrivingLicenceNumber,
    required this.ukDrivingLicenceNumberExpiryDate,
    required this.maritalStatus,
    required this.dependents,
    required this.mortgageType,
    required this.mortgageProductType,
    required this.startDateOfMortgage,
    required this.maturityDateOfMortgage,
    required this.maturityDateOfInitialFixedRateOrTrackerPeriod,
    required this.currentMortgageRate,
    required this.outstandingBalanceOnMortgageGbp,
    required this.overpaymentsOnMortgageMadeInLast3YearsGbp,
    required this.propertyStreetAddress,
    required this.propertyAddressLine2,
    required this.propertyCityTownVillage,
    required this.propertyPostalZipCode,
    required this.propertyCountry,
    required this.currentPropertyValueEstimate,
    required this.typeOfProperty,
    required this.typeOfFlat,
    required this.approximateYearOfConstruction,
    required this.newBuildWarrantyProvider,
    required this.isYourPropertyAffectedByCladdingIssues,
    required this.anyOtherCoOwnersOfThisProperty,
    required this.howManyCoOwnersOfThisProperty,
    required this.anyOtherAdultsResidingInTheProperty,
    required this.howManyAdultsOtherThanYouResideInTheProperty,
    required this.statusOfEmployment,
    required this.plannedRetirementAge,
    required this.currentEmployerName,
    required this.jobDesignation,
    required this.howLongHaveYouBeenEmployedInThisJobInMonths,
    required this.annualIncomeFromCurrentEmploymentInGbp,
    required this.additionalIncomeSources,
    required this.additionalWorkRelatedPayments,
    required this.overtimePaymentsGbp,
    required this.frequencyOfOvertimePayments,
    required this.bonusPaymentsGbp,
    required this.frequencyOfBonusPayments,
    required this.commissionPaymentsGbp,
    required this.frequencyOfCommissionPayments,
    required this.allowanceAmountsGbp,
    required this.frequencyOfAllowancePayments,
    required this.otherSourcesOfIncome,
    required this.pensionAmountsGbp,
    required this.frequencyOfPensionPayments,
    required this.investmentsGbp,
    required this.frequencyOfPaymentsFromInvestments,
    required this.disabilityBenefitsGbp,
    required this.frequencyOfDisabilityBenefits,
    required this.otherStateBenefitsGbp,
    required this.frequencyOfOtherStateBenefits,
    required this.maintenancePaymentsGbp,
    required this.frequencyOfMaintenancePayments,
    required this.chooseWhichBorrowingsApplyToYourCircumstances,
    required this.whatIsTheOutstandingBalanceOnTheStudentLoanGbp,
    required this.whatAreTheMonthlyPaymentsDueOnTheStudentLoanGbp,
    required this.whatIsTheOutstandingBalanceOnTheUnsecuredPersonalLoanGbp,
    required this.whatAreTheMonthlyPaymentsDueOnTheUnsecuredPersonalLoanGbp,
    required this.whatIsTheRemainingTermOnTheUnsecuredPersonalLoanMonths,
    required this.whatIsTheOutstandingBalanceOnTheSecuredPersonalLoanGbp,
    required this.whatAreTheMonthlyPaymentsDueOnTheSecuredPersonalLoanGbp,
    required this.whatIsTheRemainingTermOnTheSecuredPersonalLoanMonths,
    required this.whatIsTheOutstandingBalanceOnTheCreditAgreementGbp,
    required this.whatAreMonthlyPaymentsDueOnTheCreditAgreementGbp,
    required this.whatIsTheRemainingTermOnTheCreditAgreementMonths,
    required this.whatIsTheOutstandingBalanceOnTheCarLoanGbp,
    required this.whatAreTheMonthlyPaymentsDueOnTheCarLoanGbp,
    required this.whatIsTheRemainingTermOnTheCarLoanMonths,
    required this.whatIsTheOutstandingBalanceOnTheLoanGuaranteesGbp,
    required this.whatAreTheMonthlyPaymentsDueOnTheLoanGuaranteesGbp,
    required this.whatIsTheRemainingTermOnTheLoanGuaranteesMonths,
    required this.creditReference,
    required this.cardsAndDebt,
    required this.clickHereIfYouPayOffYourCreditCardBalanceEveryMonth,
    required this.whatIsTheOutstandingCreditCardBalanceGbp,
    required this.whatIsYourOverdraftBalanceGbp,
    required this.committedExpenses,
    required this.councilTaxPaymentsMonthFor10MonthsGbp,
    required this.buildingInsuranceYearGbp,
    required this.groundRentYearGbp,
    required this.serviceChargesYearGbp,
    required this.maintenancePaymentsYearGbp,
    required this.schoolFeesYearGbp,
    required this.dayCareOrNurseryFeesYearGbp,
    required this.yourSpecificRequirement,
    required this.monthlyMortgageOrCostOfLivingHelpNeededInGbp,
    required this.lengthOfTimeInMonthsYouNeedPauzibleSMortgageHelpPaymentsForMaxOf60Months,
    required this.productMaturityMaturityOfPauzibleSMortgageHelpProduct,
    required this.monthlyCashPaymentsNeededByYouInGbp,
    required this.lengthOfTimeInMonthsYouNeedPauziblePaymentsForMaxOf60Months,
    required this.productMaturityMaturityOfDesiredPauzibleProduct,
    required this.otherSourcesOfIncomeOtherOption,
    required this.chooseWhichBorrowingsApplyToYourCircumstancesOtherOption,
    required this.committedExpensesOtherOption,
  });

  Object? toJson() {}
}
